#!/usr/bin/env sh
# This file is part of libertine. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/libertine-linux/libertine/master/COPYRIGHT. No part of libertine, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2016 The developers of libertine. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/libertine-linux/libertine/master/COPYRIGHT.


_program()
{
	core_usesIn libertine check architecture path compile env configsite cmake hash
	core_dependency_requires '*' uname rm mkdir
	libertine()
	{
		umask 0000
		
		libertine_ccachePath="$_program_path"/ccache
		libertine_machinesOutputFolderPath="$_program_path"/output
		
		. "$libertine_configuration"
		
		libertine_machinesFolderPath="$libertine_machinesPath"
		libertine_machineFolderPath="$libertine_machinesFolderPath"/"$libertine_machine"
		libertine_machineSettingsFolderPath="$libertine_machineFolderPath"/settings
		libertine_machinePackageConfigurationsFolderPath="$libertine_machineFolderPath"/package-configurations
		libertine_machineInputPackagesPath="$libertine_machineFolderPath"/packages
				
		libertine_machineOutputFolderPath="$libertine_machinesOutputFolderPath"/machines/"$libertine_machine"
		libertine_machineOutputPackagesFolderPath="$libertine_machineOutputFolderPath"
		
		libertine_packageLocksOutputFolderPath="$libertine_machinesOutputFolderPath"/.package-locks
		
		# Do not change this; must be relative to libertine_machineOutputPackagesFolderPath, ie ../../.package-cache
		libertine_packageCacheOutputFolderPath="$libertine_machinesOutputFolderPath"/.package-cache
		libertine_packageCacheOutputFolderPath_relative_to_libertine_machineOutputPackagesFolderPath=../../.package-cache
		
		libertine_check_pathsDoNotHaveSpacesInThemAsAutoconfEtcToolsDoNotProperlyHandleThem
		
		mkdir -m 0700 -p \
			"$libertine_machinesOutputFolderPath" \
			"$libertine_machineOutputFolderPath" \
			"$libertine_machineOutputPackagesFolderPath" \
			"$libertine_packageLocksOutputFolderPath" \
			"$libertine_packageCacheOutputFolderPath"
		
		# TODO: Document this 'hack' - we have to know this data in advance of using musl-cross-make
		. "$libertine_machineInputPackagesPath"/musl_cross_make/compiler-details
		
		
		libertine_architecture_configure
		libertine_compile_configure
		libertine_originalPATH="$PATH"
		libertine_env_cleanse
		
		libertine_preparePackageTemporaryFolder
		
		libertine_compile_addLockTrapHandler
		libertine_compile
	}

	libertine_preparePackageTemporaryFolder()
	{
		local TMP_FOLDER
		core_temporaryFiles_newFolderToRemoveOnExit
		libertine_packagesTemporaryFolderPath="$TMP_FOLDER"
	}
}

_program_path_find()
{
	if [ "${_program_fattening_program_path+set}" = 'set' ]; then
		printf '%s\n' "$_program_fattening_program_path"

	elif [ "${0%/*}" = "$0" ]; then

		# We've been invoked by the interpreter as, say, bash program
		if [ -r "$0" ]; then
			pwd -P
		# Clutching at straws; probably run via a download, anonymous script, etc, weird execve, etc
		else
			printf '\n'
		fi

	else

		# We've been invoked with a relative or absolute path (also when invoked via PATH in a shell)

		_program_path_find_parentPath()
		{
			parentPath="${scriptPath%/*}"
			if [ -z "$parentPath" ]; then
				parentPath='/'
			fi
			cd "$parentPath" 1>/dev/null
		}

		# pdksh / mksh have problems with unsetting a variable that was never set...
		if [ "${CDPATH+set}" = 'set' ]; then
			unset CDPATH
		fi

		if command -v realpath 1>/dev/null 2>/dev/null; then
			(
				scriptPath="$(realpath "$0")"

				_program_path_find_parentPath
				pwd -P
			)
		elif command -v readlink 1>/dev/null 2>/dev/null; then
			(
				scriptPath="$0"

				while [ -L "$scriptPath" ]
				do
					_program_path_find_parentPath
					scriptPath="$(readlink "$scriptPath")"
				done

				_program_path_find_parentPath
				pwd -P
			)
		else
			# This approach will fail in corner cases where the script itself is a symlink in a path not parallel with the concrete script
			(
				scriptPath="$0"

				_program_path_find_parentPath
				pwd -P
			)
		fi

	fi
}

_program_name='libertine'
_program_version='unversioned'
_program_package_or_build=''
_program_path="$(_program_path_find)"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='libertine'

_program_commandLine_parseInitialise()
{
	_program_default_machine='example'
	_program_default_machinesPath="$_program_path"/machines
	_program_default_makeDebug=false
	_program_default_configuration="$_program_etcPath"/shellfire/libertine/libertine.config
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]..."
	_program_commandLine_helpMessage_description="Builds a Libertine Linux all-in-one kernel for a machine"
	_program_commandLine_helpMessage_options="
  -m, --machine NAME        Defaults to ${_program_default_machine}.
  -p, --machines-path PATH  PATH to parent folder of machine. Defaults to ${_program_default_machinesPath}
  -d, --make-debug          Forces make to run serially. Defaults to off.
  -c, --configuration FILE  Path to FILE containing build machine configuration. Defaults to ${_program_default_configuration}"
    _program_commandLine_helpMessage_optionsSpacing='   '
	_program_commandLine_helpMessage_configurationKeys="
  libertine_machine       Equivalent to --machine
  libertine_machinesPath  Equivalent to --machines-path
  libertine_makeDebug     Equivalent to --make-debug (if =true)
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} -- root=/dev/vda
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		m|machine)
			echo 'yes-argumented'
		;;
		
		p|machines-path)
			echo 'yes-argumented'
		;;
		
		d|debug)
			echo 'yes-argumentless'
		;;
		
		c|configuration)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	case "$optionName" in
		
		d|debug)
			_program_default_makeDebug=true
		;;
		
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		m|machine)
			libertine_machine="$optionValue"
		;;
		
		m|machines-path)
			core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			libertine_machinesPath="$optionValue"
		;;
		
		c|configuration)
			core_validate_filePathReadable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			libertine_configuration="$optionValue"
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	core_variable_array_initialise libertine_nonOptions
	core_variable_array_append libertine_nonOptions "$@"
}

_program_commandLine_validate()
{
	if core_variable_isUnset libertine_machine; then
		libertine_machine="$_program_default_machine"
	else
		:
	fi
	
	if core_variable_isUnset libertine_machinesPath; then
		libertine_machinesPath="$_program_default_machinesPath"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'libertine_machinesPath' "$libertine_machinesPath"
	fi
	
	if core_variable_isUnset libertine_makeDebug; then
		libertine_makeDebug="$_program_default_makeDebug"
	else
		:
	fi
	
	if core_variable_isUnset libertine_configuration; then
		libertine_configuration="$_program_default_configuration"
	else
		core_validate_filePathReadable $core_commandLine_exitCode_CONFIG 'configuration setting' 'libertine_configuration' "$libertine_configuration"
	fi
}

# Assumes pwd, and so requires this code to be running from this folder
. "$_program_libPath"/shellfire/core/init.functions "$@"
